title: Robot-Chinwag
description: Musings on AI, data science and tooling
author: Josh Levy-Kramer
github: https://github.com/joshlk/www.robotchinwag.com
about: Musings on AI, data science and algorithm design
disqus_shortname: robotchinwag
google_analytics: UA-131440321-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    #- icon: fa-twitter
    #  link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/joshlevykramer"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/1110328/joshlk"
    - icon: fa-github
      link: "https://github.com/joshlk"

#share:
#  twitter_username: agusmakmun6
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: RSS Feed
      url: /feed.xml

url: "https://www.robotchinwag.com"
baseurl: "https://www.robotchinwag.com"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
